development:
  host: localhost
  port: 27017
  database: exif_dev
  logfile: development.log
    
production:
  host: localhost
  port: 27017
  database: exif_prod
  logfile: production.log
    
environment: development

